(in-package #:self-improving-agent-harness/tests)

(defun logging-test-session-path (directory session-id)
  (merge-pathnames
   (format nil "~A.jsonl" session-id)
   directory))

(defun only-jsonl-files (directory)
  (remove-if-not
   (lambda (path)
     (string= "jsonl" (string-downcase (or (pathname-type path) ""))))
   (uiop:directory-files directory)))

(defun run-logging-tests ()
  (let* ((directory #P"/tmp/self-improving-agent-harness-logging-test/")
         (session-id "2026-01-01T00:00:00.001Z")
         (path (logging-test-session-path directory session-id)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging
            directory :session-id session-id)
           (self-improving-agent-harness::log-interaction
            :info "turn-received" :content "OPENROUTER_API_KEY=sk-test-do-not-persist")
           (self-improving-agent-harness::log-interaction
            :error "turn-failed" :message "Tool handler \"run_shell\" failed.")
           (let ((content (uiop:read-file-string path)))
             (ensure-true (probe-file path)
                          "interaction log uses a per-session $ISO-TIMESTAMP.jsonl file")
             (ensure-true (search "\"type\":\"user\"" content)
                          "interaction log uses Claude-style type=user for turns")
             (ensure-true (search "\"type\":\"system\"" content)
                          "interaction log uses Claude-style type=system for failures")
             (ensure-true (search "\"sessionId\":" content)
                          "interaction log includes camelCase sessionId via openrouter-json")
             (ensure-true (search "\"parentUuid\":" content)
                          "interaction log includes Claude-style parentUuid linkage")
             (ensure-true (search "\"uuid\":" content)
                          "interaction log includes a per-record uuid")
             (ensure-true (search "turn-received" content)
                          "interaction log retains the turn lifecycle event")
             (ensure-true (not (search "sk-test-do-not-persist" content))
                          "interaction log excludes secret-bearing turn content")
             (ensure-true (not (search "Tool handler \\\"run_shell\\\" failed." content))
                          "interaction log excludes arbitrary failure details")
             (ensure-true (not (probe-file (merge-pathnames "chat.log" directory)))
                          "legacy shared chat.log is no longer written")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-turn-logging-test/")
         (session-id "2026-01-01T00:00:00.002Z")
         (path (logging-test-session-path directory session-id))
         (backend (make-instance 'scripted-backend :name "scripted" :responses '()))
         (session (make-chat-session :backend backend :model "test/model" :handlers '())))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging
            directory :session-id session-id)
           (handler-case
               (chat-session-turn session "trigger a scripted backend failure")
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "turn-received" content)
                          "chat session logs the received user turn")
             (ensure-true (search "turn-failed" content)
                          "chat session logs failed turns")
             (ensure-true (not (search "Test backend exhausted" content))
                          "chat session excludes the backend failure detail")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-tool-logging-test/")
         (session-id "2026-01-01T00:00:00.003Z")
         (path (logging-test-session-path directory session-id))
         (arguments (make-hash-table :test #'equal)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (setf (gethash "command" arguments) "exit 9")
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging
            directory :session-id session-id)
           (handler-case
               (run-shell-tool arguments)
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "tool-call" content)
                          "shell tool logs its command invocation")
             (ensure-true (search "\"type\":\"tool\"" content)
                          "shell tool events use Claude-style type=tool")
             (ensure-true (search "tool-failed" content)
                          "shell tool logs failed command execution")
             (ensure-true (not (search "exit 9" content))
                          "shell tool log excludes the failing command")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-correlation-logging-test/")
         (session-id "2026-01-01T00:00:00.004Z")
         (path (logging-test-session-path directory session-id)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging
            directory :session-id session-id)
           (let ((self-improving-agent-harness::*interaction-turn-number* 2))
             (self-improving-agent-harness::log-interaction :info "turn-completed")
             (let ((*error-output* (make-string-output-stream)))
               (dolist (event '("turn-submitted" "turn-completed" "turn-failed" "turn-empty"))
                 (self-improving-agent-harness:emit-chat-event event))
               (let ((events (get-output-stream-string *error-output*)))
                 (ensure-true (search (format nil "\"session_id\":\"~A\"" session-id) events)
                              "chat boundary events include their session ID")
                 (ensure-true (search "\"turn\":2" events)
                              "chat boundary events include their submitted turn number")
                 (dolist (event '("turn-submitted" "turn-completed" "turn-failed" "turn-empty"))
                   (ensure-true (search event events)
                                "chat boundary event states remain distinguishable")))))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search (format nil "\"sessionId\":\"~A\"" session-id) content)
                          "per-session diagnostic log includes the session ID")
             (ensure-true (search "\"turn\":2" content)
                          "per-session diagnostic log includes the turn number")
             (ensure-true (search "\"type\":\"assistant\"" content)
                          "turn-completed maps to Claude-style type=assistant")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  ;; Non-timestamp preferred ids still get an ISO-timestamp-named session file.
  (let* ((directory #P"/tmp/self-improving-agent-harness-iso-normalize-test/"))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging
            directory :session-id "event-session-16")
           (self-improving-agent-harness::log-interaction :info "session-start" :mode "interactive")
           (let* ((files (only-jsonl-files directory))
                  (correlation self-improving-agent-harness::*interaction-session-id*)
                  (file-id self-improving-agent-harness::*interaction-log-file-id*))
             (ensure-true (= 1 (length files))
                          "exactly one per-session jsonl file is created")
             (ensure-true (string= correlation "event-session-16")
                          "non-timestamp correlation ids remain available for stderr events")
             (ensure-true (self-improving-agent-harness::session-id-looks-like-iso-timestamp-p file-id)
                          "non-timestamp correlation ids still use an ISO timestamp log basename")
             (ensure-true (probe-file (logging-test-session-path directory file-id))
                          "session file path matches the ISO timestamp file id")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (format t "Interaction logging tests passed.~%")
  t)
