(in-package #:self-improving-agent-harness/tests)

(defun run-report-redaction-tests ()
  (let* ((headers (make-hash-table :test #'equal))
         (report-data
           (list :note "OPENROUTER_API_KEY=credential-value"
                 :tool-output "raw sensitive tool output"
                 :usage (list :input-tokens 7 :output-tokens 3 :cost-usd 0.0025)
                 :headers headers)))
    (setf (gethash "Authorization" headers) "Bearer credential-value")
    (let ((json (self-improving-agent-harness::report-json-string
                 (redact-report-data report-data))))
      (ensure-true (not (search "OPENROUTER_API_KEY" json))
                   "redaction removes credential markers embedded in free-form values")
      (ensure-true (not (search "credential-value" json))
                   "redaction removes credential values in nested metadata")
      (ensure-true (not (search "raw sensitive tool output" json))
                   "redaction removes tool-output fields without relying on raw naming")
      (ensure-true (search "\"input_tokens\":7" json)
                   "redaction retains input token accounting")
      (ensure-true (search "\"output_tokens\":3" json)
                   "redaction retains output token accounting")
      (ensure-true (search "\"cost_usd\":" json)
                   "redaction retains actual cost accounting"))))

(defun run-report-tests ()
  (run-report-redaction-tests)
  (let* ((directory (merge-pathnames
                     (format nil "self-improving-agent-harness-report-~D/"
                             (get-universal-time))
                     (uiop:temporary-directory)))
         (artifacts
           (self-improving-agent-harness::write-scripted-baseline-report directory))
         (json-path (getf artifacts :json-path))
         (html-path (getf artifacts :html-path))
         (json (uiop:read-file-string json-path))
         (html (uiop:read-file-string html-path)))
    (unwind-protect
         (progn
           (ensure-true (probe-file json-path)
                        "a completed scripted run writes a JSON report")
           (ensure-true (probe-file html-path)
                        "a completed scripted run writes an HTML report")
           (ensure-true (search "\"schema_version\":\"1\"" json)
                        "the JSON report has a versioned schema")
           (dolist (field '("\"task\":" "\"candidate\":" "\"model_history\":"
                            "\"tool_metadata\":" "\"usage\":" "\"evaluation\":"
                            "\"decision\":"))
             (ensure-true (search field json)
                          "the JSON report contains every required trace section"))
           (ensure-true (string= "run.json" (file-namestring json-path))
                        "the JSON artifact has its predictable filename")
           (ensure-true (string= "run.html" (file-namestring html-path))
                        "the HTML artifact has its predictable filename")
           (ensure-true (search "Submit the exact answer baseline-ok" json)
                        "the JSON report retains the task prompt")
           (ensure-true (search "answer-is-baseline-ok" json)
                        "the JSON report retains acceptance evidence")
           (ensure-true (search "offline/baseline-v1" json)
                        "the JSON report retains model identity")
           (ensure-true (search "\"input_tokens\":7" json)
                        "redaction preserves input token accounting")
           (ensure-true (search "\"output_tokens\":3" json)
                        "redaction preserves output token accounting")
           (ensure-true (search "\"cost_usd\":" json)
                        "redaction preserves actual cost accounting")
           (ensure-true (not (search "OPENROUTER_API_KEY" json))
                        "JSON reports omit credential names")
           (ensure-true (not (search "credential-value" json))
                        "JSON reports omit credential values")
           (ensure-true (not (search "raw sensitive tool output" json))
                        "JSON reports omit raw tool output")
           (ensure-true (search "Available model history" html)
                        "HTML renders available model history before attempt history")
           (ensure-true (search "Invoked model history" html)
                        "HTML renders invoked model history")
           (ensure-true (search "<table" html)
                        "HTML renders invoked model history as a table")
           (dolist (heading '("Task" "Candidate lineage" "Tool metadata" "Outcome"
                              "Evaluator evidence" "Final decision"))
             (ensure-true (search heading html)
                          "HTML renders every human-readable trace section"))
           (ensure-true (< (search "Available model history" html)
                           (search "Invoked model history" html))
                        "HTML places available models before invoked model attempts")
           (ensure-true (search "offline/baseline-v1" html)
                        "HTML is rendered from the live JSON report model")
           (ensure-true (not (search "OPENROUTER_API_KEY" html))
                        "HTML reports omit credential names")
           (ensure-true (not (search "raw sensitive tool output" html))
                        "HTML reports omit raw tool output")
           (format t "Run-report artifact and redaction tests passed.~%"))
      (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore))))
