(in-package #:self-improving-agent-harness/tests)

(defun run-shell-tool-tests ()
  (let* ((em-dash (string (code-char #x2014)))
         (expected (format nil "unicode ~A output" em-dash))
         (output
           (self-improving-agent-harness::run-shell-tool
            (let ((arguments (make-hash-table :test #'equal)))
              (setf (gethash "command" arguments)
                    "printf 'unicode \\342\\200\\224 output'")
              arguments))))
    (ensure-equal expected output
                  "shell tool decodes UTF-8 command output"))
  (let ((output
          (self-improving-agent-harness::run-shell-tool
           (let ((arguments (make-hash-table :test #'equal)))
             (setf (gethash "command" arguments)
                   "printf 'README was not found' >&2; exit 9")
             arguments))))
    (ensure-true (search "Command failed with exit status 9" output)
                 "shell tool returns a nonzero exit status to the model")
    (ensure-true (search "README was not found" output)
                 "shell tool returns combined failure output to the model"))
  (let* ((seen nil)
         (arguments (make-hash-table :test #'equal)))
    (setf (gethash "command" arguments) "printf ok; exit 3")
    (let ((self-improving-agent-harness:*run-shell-after-hooks*
            (list (lambda (&key command exit-status duration-seconds output)
                    (setf seen (list command exit-status duration-seconds output))))))
      (let ((output (self-improving-agent-harness:run-shell-tool arguments)))
        (ensure-true (search "Command failed with exit status 3" output)
                     "hook test still returns failure content")
        (ensure-true (not (null seen)) "run_shell after-hook was invoked")
        (ensure-equal "printf ok; exit 3" (first seen)
                      "hook receives the command string")
        (ensure-equal 3 (second seen) "hook receives the exit status")
        (ensure-true (and (numberp (third seen)) (>= (third seen) 0))
                     "hook receives a non-negative duration")
        (ensure-true (search "ok" (fourth seen))
                     "hook receives command output"))))
  (format t "Shell-tool tests passed.~%")
  t)
