(in-package #:self-improving-agent-harness)

;;;; Harness-owned MCP bridge for Claude Code.
;;;;
;;;; Tool schemas are projected directly from CHAT-TOOL-DEFINITIONS and execution
;;;; is dispatched through CHAT-HANDLERS.  There is intentionally no .mcp.json
;;;; file or duplicated external tool registry to drift from the Lisp harness.

(defparameter *claude-mcp-server-name* "harness"
  "The ephemeral MCP server name supplied to one Claude CLI invocation.")

(defparameter *claude-mcp-bridge-command* '("/workspace/bin/claude-mcp-bridge")
  "Command Claude Code uses to start the stdio MCP bridge in the container.")

(defun claude-mcp-object (&rest pairs)
  "Build a JSON object from string-keyed PAIRS."
  (let ((object (make-hash-table :test #'equal)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key object) value))
    object))

(defun claude-mcp-tool-specifications ()
  "Project live Lisp CHAT-TOOL-DEFINITIONS into MCP `tools/list` objects.

This is the sole schema projection.  The OpenAI-compatible definitions and the
MCP definitions therefore change together whenever CHAT-TOOL-DEFINITIONS is
reloaded; no checked-in MCP JSON configuration exists."
  (mapcar
   (lambda (definition)
     (let ((function (getf definition :function)))
       (claude-mcp-object
        "name" (getf function :name)
        "description" (getf function :description)
        "inputSchema" (openrouter-json-value (or (getf function :parameters)
                                                  '(:type "object"))))))
   (chat-tool-definitions)))

(defun claude-mcp-config-json ()
  "Return the per-invocation stdio MCP config generated by Lisp code.

The value is supplied directly to Claude's `--mcp-config`; it is not persisted
as a project/user configuration file and contains neither credentials nor tool
schemas.  Tool schemas arrive over MCP from CLAUDE-MCP-TOOL-SPECIFICATIONS."
  (let* ((command *claude-mcp-bridge-command*)
         (server (claude-mcp-object
                  "type" "stdio"
                  "command" (first command)
                  "args" (coerce (rest command) 'vector)
                  "alwaysLoad" t))
         (servers (claude-mcp-object *claude-mcp-server-name* server))
         (config (claude-mcp-object "mcpServers" servers)))
    (with-output-to-string (stream) (yason:encode config stream))))

(defun claude-mcp-jsonrpc-success (id result)
  (claude-mcp-object "jsonrpc" "2.0" "id" id "result" result))

(defun claude-mcp-jsonrpc-error (id code message)
  (claude-mcp-object "jsonrpc" "2.0" "id" id
                     "error" (claude-mcp-object "code" code "message" message)))

(defun claude-mcp-safe-text (value)
  "Render a bounded, credential-scrubbed MCP tool result."
  (let ((text (scrub-interaction-log-text (princ-to-string (or value "")))))
    (subseq text 0 (min (length text) 20000))))

(defun claude-mcp-call-tool (name arguments)
  "Dispatch one MCP tool call through the live Harness handler registry."
  (handler-case
      (let* ((handler (openrouter-tool-handler (chat-handlers) name))
             (result (funcall handler (or arguments (make-hash-table :test #'equal)))))
        (claude-mcp-object
         "content" (vector (claude-mcp-object "type" "text"
                                               "text" (claude-mcp-safe-text result)))
         "isError" yason:false))
    (error (condition)
      (claude-mcp-object
       "content" (vector (claude-mcp-object
                           "type" "text"
                           "text" (claude-mcp-safe-text
                                   (format nil "Tool ~A failed: ~A" name condition))))
       "isError" t))))

(defun claude-mcp-handle-request (request)
  "Return a JSON-RPC response object for REQUEST, or NIL for notifications."
  (let* ((id (gethash "id" request))
         (method (gethash "method" request))
         (params (gethash "params" request)))
    (cond
      ((string= method "notifications/initialized") nil)
      ((string= method "initialize")
       (claude-mcp-jsonrpc-success
        id (claude-mcp-object
            "protocolVersion" "2024-11-05"
            "capabilities" (claude-mcp-object
                            "tools" (claude-mcp-object))
            "serverInfo" (claude-mcp-object "name" "harness-lisp-bridge"
                                             "version" "1"))))
      ((string= method "tools/list")
       (claude-mcp-jsonrpc-success
        id (claude-mcp-object "tools" (coerce (claude-mcp-tool-specifications) 'vector))))
      ((string= method "tools/call")
       (let ((name (and (hash-table-p params) (gethash "name" params)))
             (arguments (and (hash-table-p params) (gethash "arguments" params))))
         (if (and (stringp name) (plusp (length name)))
             (claude-mcp-jsonrpc-success id (claude-mcp-call-tool name arguments))
             (claude-mcp-jsonrpc-error id -32602 "tools/call requires a tool name"))))
      ((null id) nil)
      (t (claude-mcp-jsonrpc-error id -32601 "method not found")))))

(defun claude-mcp-serve (&optional (input *standard-input*) (output *standard-output*))
  "Serve the stdio MCP protocol until INPUT closes.

Only JSON-RPC frames are written to OUTPUT.  Startup/loading diagnostics must be
sent to stderr by the launcher so they cannot corrupt the protocol stream."
  (let ((session-id (uiop:getenv "HARNESS_CHAT_SESSION_ID"))
        (log-directory (or (uiop:getenv "HARNESS_LOG_DIR") "/workspace/agent-logs")))
    ;; The bridge is a short-lived child process, so bind it to the parent
    ;; durable session before invoking any existing handlers that log events.
    (when (and (stringp session-id) (plusp (length session-id)))
      (configure-interaction-logging log-directory :session-id session-id)))
  (loop for line = (read-line input nil nil)
        while line
        do (handler-case
               (let* ((request (yason:parse line))
                      (method (gethash "method" request))
                      (response (claude-mcp-handle-request request)))
                 ;; Protocol diagnostics are method-only, written to stderr,
                 ;; and never include tool arguments or environment data.
                 (when (string= (or (uiop:getenv "HARNESS_MCP_TRACE") "") "1")
                   (format *error-output* "HARNESS_MCP method=~A~%" method)
                   (finish-output *error-output*))
                 (when response
                   (yason:encode response output)
                   (terpri output)
                   (finish-output output)))
             (error (condition)
               ;; A malformed request with no trustworthy id cannot be answered
               ;; safely; keep stderr diagnostic-only and continue serving.
               (format *error-output* "Harness MCP bridge request error: ~A~%" condition)
               (finish-output *error-output*)))))
